import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SesionProviders from './components/SesionProviders'
import './globals.css'
import AppBar from './components/AppBar'
import { ThemeProvider } from './components/theme-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='h-screen' lang="en">
      <body className={`${inter.className} h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <div className='xl:flex h-screen min-w-min'>
            <SesionProviders>
              <AppBar />
              {children}
            </SesionProviders>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
